# Generated by Django 3.1.6 on 2021-02-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoUnloadTimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_io_id', models.PositiveIntegerField()),
                ('date_unload', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarehousePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_num', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(choices=[('RESERVED', 'RESERVED'), ('FILLED', 'FILLED'), ('VOID', 'VOID')], default='VOID', max_length=10)),
                ('last_action', models.CharField(blank=True, choices=[('LOAD', 'LOAD'), ('UNLOAD', 'UNLOAD'), ('TRANSFER', 'TRANSFER')], default=None, max_length=10, null=True)),
                ('shelving', models.PositiveSmallIntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CargoMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_io_id', models.PositiveIntegerField(blank=True, null=True)),
                ('from_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_point', to='warehouse.warehousepoint')),
                ('to_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_point', to='warehouse.warehousepoint')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('cargo_model', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=512)),
                ('factory_io_id', models.PositiveIntegerField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehousepoint')),
            ],
        ),
    ]
