# Generated by Django 3.1.6 on 2021-02-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationcode',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
